// Code generated by Microsoft (R) AutoRest Code Generator 0.16.0.0
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.


    using System;
    using System.Linq;
    using System.Collections.Generic;
    using Newtonsoft.Json;
    using Microsoft.Rest;
    using Microsoft.Rest.Serialization;
namespace WebDemo.Models
{
    public partial class ProductCategory
    {
        /// <summary>
        /// Initializes a new instance of the ProductCategory class.
        /// </summary>
        public ProductCategory() { }

        /// <summary>
        /// Initializes a new instance of the ProductCategory class.
        /// </summary>
        public ProductCategory(string productCat = default(string), int? productCatID = default(int?), List<Product> products = default(List<Product>), string productCatImg = default(string))
        {
            ProductCat = productCat;
            ProductCatID = productCatID;
            ProductCatImg = productCatImg;
            Products = new List<Product>();
            Products.AddRange(products);
        }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "ProductCat")]
        public string ProductCat { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "ProductCatID")]
        public int? ProductCatID { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "Products")]
        public List<Product> Products { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "ProductCatImg")]
        public string ProductCatImg { get; set; }

    }
}
